type: app
description: Default stackfile usecase description
template: stack-kotlin-rest-assured/<template-name>
inputs:
  some_input: value
plugins:
  - plugin: stack-kotlin-rest-assured/<plugin-name>
    inputs:
      some_input: value
      some_list:
        - item1
        - item2
