description: Projeto destinado para fazer automações de projetos back-end usando kotlin e rest assured.
name: stack-kotlin-rest-assured
display-name: stack-kotlin-rest-assured
picture: kotlin.jpg
category: backend
compatibility: 
  - Kotlin
technologies: 
  - docker
  - rest assured
  - junit
  - javafaker
about: docs/about.md
use-cases:
  - title: Use Case Title
    stackfile: stackfiles/default.yaml