description: Projeto destinado para fazer automações de projetos back-end usando kotlin
name: stack-kotlin-rest-assured
display-name: stack-kotlin-rest-assured
picture: kotlin.jpg
category: backend
compatibility: 
  - Kotlin
technologies: 
  - docker
  - rest assured
  - junit
  - lombock
  - hamcrest
  - javafaker
about: docs/about.md
use-cases:
  - title: Use Case Title
    content: docs/use-case.md
    stackfile: stackfiles/default.yaml